import "./globals.css";
import type { Metadata } from "next";
import { Passion_One } from "next/font/google";
import styles from "./page.module.css";
import Link from "next/link";

const passionOne = Passion_One({ subsets: ["latin-ext"], weight: "400" });

export const metadata: Metadata = {
  title: "NASA API test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <Link href="/">
            <h1 className={passionOne.className}>ARMAGEDDON 2023</h1>
          </Link>
          <p>
            ООО “Команда им. Б. Уиллиса”.
            <br />
            Взрываем астероиды с 1998 года.
          </p>
        </header>
        <main className={styles.main}>
          <div className={styles.earthImg} />
          {children}
        </main>
        <footer className={styles.footer}>
          © Все права и планета защищены
        </footer>
      </body>
    </html>
  );
}
